### ISSUE TITLE
KDFs

### ISSUE THREAD

**Issue by chris-wood** [chris-wood/draft-bar-cfrg-spake2plus#11]
From @cjpatton

# Section 4

* The spec aims to work with any KDF, i.e., it does not assume that HKDF will
  always be used. That means either (1) the KDF column of Table 1 needs to
  specify the hash function in use for HKDF or (2) it needs to be spelled out
  somewhere that HKDF-based ciphersuites use the Hash algorithm as the
  underlying hash function.

**Comment by chris-wood** [comment]
This is [already done](https://github.com/chris-wood/draft-bar-cfrg-spake2plus/blob/master/draft-bar-cfrg-spake2plus.md#ciphersuites-ciphersuites). I'm realizing now that the editor's copy isn't updating based on that change, ugh. 

@cjpatton, I think we can close this. Please confirm.

**Comment by cjpatton** [comment]
This section looks the same as the version I reviewed (draft-04), in particular which hash function is used with the HKDF modes is still seems ambiguous. I suppose it's clear enough from context, but it's odd that the MAC specifies the hash function (e..g, `HMAC-SHA256`) but the KDF does not (e.g., `HKDF`).

**Comment by chris-wood** [comment]
Yep, right, I was looking at the HMAC column. We can fix this.
