### ISSUE TITLE
Empty identities

### ISSUE THREAD

**Issue by chris-wood** [chris-wood/draft-bar-cfrg-spake2plus#12]
From @cjpatton

* Quote:

  > For simplicity, if both identities are absent, i.e. len(A) = len(B) = 0,
  > then w0s || w1s = PBKDF(pw).

  This may be problematic from the perspective of the security analysis, I
  suggest we go back to the Shoup paper and check. The problem is that RO
  queries for sessions with no identities might collide with queries for
  sessions with identities. For example, a password `pw` in one session may be
  equal to `len(pw2) || pw2 || len(A) || A || len(B) || B)` where `pw2` is the
  password in another session in which `A` and `B` are the identities.

  Since this logic isn't excercised in the rest of the spec, I would just remove
  it and not treat this as a special case.

**Comment by chris-wood** [comment]
IIRC the security analysis does cover this case, though I would need to go back and double check. @ttaubert, do you recall off hand? If it does, we can safely close this without action.

**Comment by ttaubert** [comment]
The security analysis does explicitly not cover this case:

<img width="1188" src="https://user-images.githubusercontent.com/300895/151812454-d94ea7f7-2ed4-4dde-98f6-334a87e3c56d.png">

**Comment by chris-wood** [comment]
Ah, well, interesting!
