### ISSUE TITLE
Clarify bias

### ISSUE THREAD

**Issue by chris-wood** [chris-wood/draft-bar-cfrg-spake2plus#13]
From @cjpatton

* Quote:

  > The output length of the PBKDF MUST be at least 64 bits longer than than
  > that needed to represent p. This is done to remove statistical bias
  > introduced by the modular reduction. For example, given the prime order of
  > the P-256 curve, the output of the PBKDF can be 320 bits or larger.

  Three notes here, one editorial and two technical. First, this paragraph needs
  a transition sentence so that it's clear that we're going to interpret the
  output of PBKDF as an integer and reduce it.

  Second, this is bound to be a source of bugs. I think it would be worthhile to
  explicitly define the minimum output length as a function of `p`. The
  hash-to-curve draft has to deal with the same thing
  (https://datatracker.ietf.org/doc/html/draft-irtf-cfrg-hash-to-curve#section-5.3)
  so it might be worth cribbing off of that.

  Third, I don't think it would be clear for an implementor why this is
  important. On the other hand, a cryptographer might argue that this strategy
  is algorithm is sub-optimal, either in terms of efficiency or the biased
  induced. I think a bit of discussion about where the bias comes from, as well
  as a link to an analysis that relates the minimum output length to the bias
  induced by modular reduction, would be useful.

**Comment by chris-wood** [comment]
> Second, this is bound to be a source of bugs. I think it would be worthhile to explicitly define the minimum output length as a function of p. The hash-to-curve draft has to deal with the same thing (https://datatracker.ietf.org/doc/html/draft-irtf-cfrg-hash-to-curve#section-5.3) so it might be worth cribbing off of that.

Being explicit here is a good improvement.

> Third, I don't think it would be clear for an implementor why this is important. On the other hand, a cryptographer might argue that this strategy is algorithm is sub-optimal, either in terms of efficiency or the biased induced. I think a bit of discussion about where the bias comes from, as well as a link to an analysis that relates the minimum output length to the bias induced by modular reduction, would be useful.

I don't think this is necessary. @cjpatton, why would this be useful to an implementer?

**Comment by cjpatton** [comment]
I suppose it matters less to an implementer, but for someone who is trying to understand the security of this thing, I do think it's important to understand what bias is induced, why that bias is acceptable, and why this algorithm was picked over other strategies.

**Comment by chris-wood** [comment]
> I suppose it matters less to an implementer, but for someone who is trying to understand the security of this thing, I do think it's important to understand what bias is induced, why that bias is acceptable, and why this algorithm was picked over other strategies.

The point is that there is _no_ bias introduced, and sampling more bits is the way to address that. I don't think we need to explain why this was chosen over other techniques like rejection sampling.

**Comment by cjpatton** [comment]
Oh, I see. You mean that the following text claims that there is *no bias* (i.e., that all integers in [0, p) are equiprobable): 

> The output length of the PBKDF MUST be at least 64 bits longer than than that needed to represent p. This is done to remove statistical bias introduced by the modular reduction.

In that case I would say that this claim isn't self-evident and needs to be justified.

**Comment by chris-wood** [comment]
I'm saying I disagree that we need to include additional rationale here (rather than simply citing something), much like one doesn't explain why, say, AES is a secure PRP when used.

**Comment by cjpatton** [comment]
Yes, a citation would be sufficient justification, but I would also suggest clarifying whether you mean that the statistical bias is completely eliminated or is merely reduced. My original reading was that the bias was reduced (and I wondered by how much), but based on this conversation, it sounds like the bias is completely eliminated (and if so, I want to understand why).

**Comment by chris-wood** [comment]
> My original reading was that the bias was reduced (and I wondered by how much), but based on this conversation, it sounds like the bias is completely eliminated (and if so, I want to understand why).

The bias is made _negligible_, not eliminated entirely. I don't think the draft needs to provide proof of this. We can merely cite something else.

**Comment by cjpatton** [comment]
My ask is to sharpen the text to clarify that the bias is not completely eliminated but is negligible, and add a reference that supports this.

**Comment by chris-wood** [comment]
Lovely -- thanks 👍
