### ISSUE TITLE
how is K_enc produced?

### ISSUE THREAD

**Issue by Kxuan** [chris-wood/draft-bar-cfrg-spake2plus#31]
The document says:

> Once key confirmation is complete, applications MAY use K_enc as an authenticated shared secret as needed. For example, applications MAY derive one or more AEAD keys and nonces from K_enc for subsequent application data encryption.

But the document does not explicit says how to produce `K_enc`.

**Comment by ttaubert** [comment]
Thanks! Those `K_enc` references need to be removed indeed.
