### ISSUE TITLE
Key confirmation methods

### ISSUE THREAD

**Issue by chris-wood** [chris-wood/draft-bar-cfrg-spake2plus#6]
From @cjpatton

* Quote:

  > Both endpoints MUST either exchange cA=KcA and cB=KcB directly, or employ a
  > secure PRF, acting as a MAC that produces pseudorandom tags, for key
  > confirmation. In the latter case, KcA and KcB are symmetric keys used to
  > compute tags cA and cB over data shared between the participants.

  Two methods for key confirmation are permitted. If the first method is
  sufficient (just sending the confirmation key directy), then why bother with
  the MAC? In particular because [SPAKE2P-Analysis] takes the first method,
  what value is added by the second?

  From an implementor's perspective, I think that a choice here is confusing, as
  it's not immediately clear what are the security implications of the choice.
  As a cryptographer, it's fairly clear to me that the second method is no less
  secure then the first, but an implementor might well believe that the first
  method is open to an attack that the second isn't.

  I'd recommend specifying just one of these methods. If you're going to leave
  this choice to the implementor, it would be best to make clear the pros and
  cons of each method. In addition, for the second method, being more
  perscriptive would be useful. Right now it says:

  > [In the second method,] KcA and KcB are symmetric keys used to compute tags
  > cA and cB over data shared between the participants. That data could for
  > example be an encoding of the key shares exchanged earlier, or simply a
  > fixed string.

  As an implementor, I would prefer to have the MAC data spelled out, since it's
  not clear to me what the security implications are of whatever I choose to
  MAC. Maybe just mandate what's in the test vectors?

  Finally, niit: A MAC is sufficient, I don't think there's a need to use the
  acronym "PRF" here. (This is the only place it's used in the document.)

**Comment by ttaubert** [comment]
#20 updates the spec to be more prescriptive about MAC inputs, which I fully agree is a good thing for implementors. I'd prefer computing a MAC over the exchanged key shares, that's what we use for our tests vectors too, as @cjpatton pointed out.
