### ISSUE TITLE
Editorial things

### ISSUE THREAD

**Issue by chris-wood** [chris-wood/draft-bar-cfrg-spake2plus#7]
From @cjpatton

# Section 1

* "verification value" doesn't quite capture the semantics of the server's
  input. It's also not clear why this would hide the password. (The reason the
  password is hard to compute is that all the server has is its image under a
  one-way function.) I would instead call this the "record" to align with the
  OPAQUE spec.

* s/initialization phase/registration phase/ to align with the OPAQUE spec.

* s/can not/cannot/

# Section 3

* Editorial: Variables A and B are used for the identities. Group elements are
  similarly denoted by single capital letters. This makes the spec hard to read,
  because my brain has to remember that A and B aren't curve points. I would
  suggest picking different names, such as idProver and idVerifier or something.

## 3.1

* s/little- endian/little endian/

## 3.3

* This is a bit confusing:

  > At the end, A stores w0 and w1, ...

  Thinking of A as the client, the client doesn't need to store `w0` and `w1`
  long term, it just needs to derive them from the password before the protocol
  begins. I would instead write "A derives w0 and w1 from the password, ...".

* Quote:

  > Both w0 and w1 are computed using a function that is indistinguishable from a
  > random oracle, which means that w0 and w1 are indistinguishable from two
  > uniformly random elements in the range [0, p-1]. See [SPAKE2P-Analysis] for
  > details.

  A functionn can't be said to be indistinguishable from a random oracle, since
  it's computed by a deterministic algorithm. I would rewrite this as "Both w0
  and w1 are derived using a function with range [0, p-1] and which is modeled
  as a random oracle in [SPAKE2P-Analaysis]."

## 3.4

* nit: In this seciton `[0, p)` is used to denote the set of integers between 0
  and p (exclusive). Above, `[0, p-1]` is used to denote the same set. I would
  be consistent.

* Quote:

  > All proofs of security hold even if the discrete log of the fixed group
  > element N is known to the adversary. In particular, one MAY set N=I, i.e.
  > set N to the unit element in G.

  I'm not sure this is true. In any case, this contradicts the following
  statement from Section 3.1:

  > Importantly, [the algorithm that generates constants M and N] chooses M and
  > N such that their discrete log is not known. P is specified in the document
  > defining the group, and so we do not repeat it here.

* Quote:

  > If an identity is absent, its length is given as zero and the identity
  > itself the empty octet string. If both A and B are absent, then both lengths
  > are zero and both A and B will be empty octet strings.

  Aren't A and B the identities? Should "identity" instead by "Context" here?

## 3.5

* Quote:

  > The length of each key is equal to half of the digest output, e.g., |Ke| =
  > |Ka| = 128 bits for SHA-256.
  >
  > Ka || Ke = Hash(TT)
  > KcA || KcB = KDF(nil, Ka, "ConfirmationKeys")

  The length of Ka and Ke are defined, but what about KcA and KcB? It seems like
  what you want here is for the output length of KDF to be the same as Hash and
  for |KcA| = |KcB| = |Ka|.

  Instead of "digest output" do you mean the length of the KDF's output? Perhaps

# Section 4

* There is a reference in this section for the NIST-curve standards but not for
  edwards25519 or edwards448. [RFC8032] would be suitable.

* Editorial: The definitions of the points are not rendered properly in HTML. I
  believe you need to put a blank line before the "~~~".

# Section 6

  Finally, I would replace this paragraph with more standard boiler plate:

  > The choices of random numbers MUST BE uniform. Randomly generated values
  > (e.g., x and y) MUST NOT be reused; such reuse may permit dictionary attacks
  > on the password.

  For example: "The ephemeral randomness used by the prover and verifier MUST be
  generated using a cryptographically secure CSPRNG."

# Appendix A

* Editorial: This section looks to be identical to the same section in the
  SPAKE2 document. Why not just reference it there?

**Comment by ttaubert** [comment]
> Editorial: This section looks to be identical to the same section in the
> SPAKE2 document. Why not just reference it there?

I'll leave this in for now. SPAKE2 is still a draft so I don't think we can just reference it?

>> All proofs of security hold even if the discrete log of the fixed group
>> element N is known to the adversary. In particular, one MAY set N=I, i.e.
>> set N to the unit element in G.

> I'm not sure this is true.

From [SPAKE2P-Analysis]:
<img width="736" src="https://user-images.githubusercontent.com/300895/152796207-cb56b0de-f81c-48de-916a-8320861d8926.png">

> In any case, this contradicts the following statement from Section 3.1:

>> Importantly, [the algorithm that generates constants M and N] chooses M and
>> N such that their discrete log is not known. P is specified in the document
>> defining the group, and so we do not repeat it here.

I don't think this paragraph is contradicting the previous statement. I says the algorithm is choosing M,N such that their dlog is unknown, but not explicitly why. We don't *need* to do that for N but it doesn't hurt either.
